apiVersion : apps/v1
kind: Deployment
metadata:
  name: srinitest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srinitest
  template:
    metadata:
      labels:
        app: srinitest 
    spec:
      containers:
        - name: srinitest 
          image: buildachart.azurecr.io/srinitest
          ports:
          - containerPort: 5282